### ISSUE TITLE
Loading wav files.

### ISSUE THREAD

**Issue by KoertGaaikema** [igorski/MWEngine#22] opened 2016-12-08 09:42 UTC
Hi,

I'm working on a small Android project, and this engine seems to fit my needs !

I've been playing with it and after some changes I was able to compile it.

Now I'm trying to load some wav files to simply loop / sequence. But I can't get it done somehow.
I couldn't load them from the assets or res or local filesystem of my phone.

Is there a more hands on example that I can follow, or can someone  point me in the correct direction ?

Koert.

**Comment by igorski** [comment] 2016-12-08 10:17
Hi @KoertGaaikema , have you tried the introduction on sample based content in the Wiki: https://github.com/igorski/MWEngine/wiki/Example-:-Creating-a-simple-drum-machine ? What you need is an instance of SampledInstrument that can play back samples that are registered inside the SampleManager.

I am tempted to extend the example Activity in this repository though as I can see the benefit of including an example on working with sample based sequencing. Would you agree that adding a simple kick/snare pattern to the existing demo Activity could be of help ?

**Comment by KoertGaaikema** [comment] 2016-12-08 10:29
Yes, I've got all of that set up !

And did read most of the wiki already :D 

At the start of my app I copy all audio files to the local filesystem of my phone now , and load them from there ( not the nicest solution, but at least I can get to the files via JavaUtilities.createSampleFromFile )
The main error I get now is "WaveReader::Error not a valid WAVE file (no RIFF header)"
And I'm pretty sure it's a valid wav file ( I use the same files in a IOS app )

But I prefer to just load them from the assets folder directly.

It would be really helpful to add a working example indeed where you actually load wav files. 
Much appreciated!

I'm purely working with the java side of the repo btw, since c++ is new to me ;)

Btw, to make the thing compile I had to add "-latomic" to line 81 of AndroidMK

`LOCAL_LDLIBS := -llog -lOpenSLES -latomic`

Not sure if it only applies to my machine / setup though ...

K.

**Comment by igorski** [comment] 2016-12-09 12:05
Hello again!

I understand the issue. Depending on how you copied your resources it is possible the files aren't actual WAV files when they are copied onto the local filesystem (assets are compressed when packaged inside an .APK, unless you add them as a resource to the _/res/raw_ folder).

However, it is obviously not ideal to have to copy your package contents onto the filesystem. I have created a new function in JavaUtilities called _createSampleFromAsset_. This method allows you to pass the String name of the asset which will then be loaded directly from the APK's _/assets_ folder (making it possible to use compression for your assets, which is nice, but also to not have to temporarily store data on the device's file system, which is even nicer).

This development is currently on this feature branch: https://github.com/igorski/MWEngine/tree/samples

You can check the branch out and view _MWEngineActivity.java_ for an example on how to use the new _createSampleFromAsset_-method (lines 139 onwards). I hope this also addresses the issue you had with the corrupt WAV file (try replacing one of the .wav files in the repository's _/assets/_ folder with your file to see if the issue is resolved).

I have also added your "-latomic" addition to the make files, it is a requirement for the new NDK.

**Comment by KoertGaaikema** [comment] 2016-12-09 15:21
Cool !

It works like a charm ! 
Really straight forward now.
Thanks !

I've got one more question ( maybe a few more when I dive into it :D ) .

Is it possible to change rate / pitch of a SampledInstrument ?
So I can use a simple wav as an actual instrument and play different notes ?

K.

**Comment by igorski** [comment] 2016-12-10 09:59
Hi @KoertGaaikema I will close this issue as the original one has been resolved. If you can send me a message via the form on https://igorski.nl/contact we can have a look at your pitch shifting question :)

**Closed by igorski** 2016-12-10 09:59 UTC
